kind: pipeline
name: default

steps:
  - name: compile
    image: maven:3-eclipse-temurin-21
    commands:
      - mvn -B clean compile
    when:
      branch:
        - main
        - develop
        - feature/*
        - fix/*
        - release/*
  - name: unit-tests
    image: maven:3-eclipse-temurin-21
    commands:
      - mvn -B test
    when:
      branch:
        - develop
        - feature/*
        - fix/*
  - name: setup-vault
    image: alpine:latest
    environment:
      VAULT_VERSION: 1.17.6
    commands:
      - wget -q -O vault_$${VAULT_VERSION}_linux_amd64.zip https://releases.hashicorp.com/vault/$${VAULT_VERSION}/vault_$${VAULT_VERSION}_linux_amd64.zip
      - wget -q -O - https://releases.hashicorp.com/vault/$${VAULT_VERSION}/vault_$${VAULT_VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -c
      - mkdir -p .bin
      - unzip vault_$${VAULT_VERSION}_linux_amd64.zip -d .bin
      - rm vault_$${VAULT_VERSION}_linux_amd64.zip
    when:
      branch:
        - main
        - release/*
  - name: unit-integration-tests
    image: maven:3-eclipse-temurin-21
    environment:
      VAULT_VERSION: 1.17.6
    commands:
      - export PATH=$${DRONE_WORKSPACE}/.bin:$${PATH}
      - mvn -B -P integration-test verify
    when:
      branch:
        - main
        - release/*
